Models/Faculty.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faculty
    {
        public int Employee_ID { get; set; }
        public string Organization_Name { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Job_Title { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int IsActive { get; set; }
        public byte[] Photo { get; set; }
        public string Address { get; set; }
        public string Phone_Number { get; set; }
        public string Meal_Plan { get; set; }
        public bool Meal_Plan_Status { get; set; }
    
        public virtual Plan Plan { get; set; }
    }
}

Controllers/Administrators/FacultyController.cs
using POS.Datos;
using POS.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace POS.Controllers
{
    public class FacultyController : Controller
    {
        FacultyAdmin admin = new FacultyAdmin();

        // GET: Faculty
        public ActionResult Index()
        {
            return View(admin.Consultar());
        }

        [HttpGet]
        public ActionResult Nuevo()
        {
            ViewBag.Meal_Plan = GetPlanesSelect();
            admin.Consultar();
            return View();
        }

        [HttpPost]
        [ActionName("Guardar")]
        public ActionResult NuevoPost(Faculty empleado)
        {
            admin.Consultar();
            if (ModelState.IsValid)
                {
                Cafeteria_POSEntities context = new Cafeteria_POSEntities();
                admin.Consultar();
                context.Faculties.Add(empleado);
                context.SaveChanges();
                ViewBag.mensaje = "Informacion Guardada";
                return RedirectToAction("Index");
                }
            return View(empleado);
        }
        
        public ActionResult Guardar() // HTTP GET
        {
            ViewBag.mensaje = "";
            ViewBag.Meal_Plan = GetPlanesSelect();
            return View();
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            Cafeteria_POSEntities context = new Cafeteria_POSEntities();
            Faculty empleado = context.Faculties.Single(x => x.Employee_ID == id); 
            ViewBag.Meal_Plan = GetPlanesSelect();
            return View(empleado);
        }

        [HttpPost]
        [ActionName("Editar")]
        public ActionResult Editar(Faculty empleado, int id)
        {
            if (ModelState.IsValid)
            {
                Cafeteria_POSEntities context = new Cafeteria_POSEntities();
                empleado = context.Faculties.Single(x => x.Employee_ID == id);
                context.Entry(empleado).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(empleado);
        }

        public IEnumerable<SelectListItem> GetPlanesSelect()
        {
            using (Cafeteria_POSEntities Context = new Cafeteria_POSEntities())
            {
                return Context.Plans.Select(plan => new SelectListItem { Value = plan.Plan_Name, Text = plan.Plan_Name }).ToList();
            }
        }

        [HttpGet]
        public ActionResult Detalles(int id)
        {
            if (ModelState.IsValid)
            {
                Cafeteria_POSEntities context = new Cafeteria_POSEntities();
                Faculty empleado = context.Faculties.Single(x => x.Employee_ID == id);
                ViewBag.Meal_Plan = GetPlanesSelect();
                admin.Consultar();
                return View(empleado);
            }
            return View("Detalles");
        }
        [HttpPost]
        [ActionName("Detalles")]
        public ActionResult DetallesPost(int id)
        {
            if (ModelState.IsValid)
            {
                Cafeteria_POSEntities context = new Cafeteria_POSEntities();
                Faculty empleado = context.Faculties.Single(x => x.Employee_ID == id);
                ViewBag.Meal_Plan = GetPlanesSelect();
                admin.Consultar();
                return View(empleado);
            }
            return View("Detalles");
        }

        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            Cafeteria_POSEntities context = new Cafeteria_POSEntities();
            Faculty empleado = context.Faculties.Single(x => x.Employee_ID == id);
            return View(empleado);
        }

        [HttpPost]
        [ActionName("Eliminar")]
        public ActionResult EliminarConfirm(int id)
        {
            Cafeteria_POSEntities context = new Cafeteria_POSEntities();
            Faculty empleado = context.Faculties.Single(x => x.Employee_ID == id);
            context.Faculties.Remove(empleado);
            context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Iniciar Sesion")]
        [ValidateAntiForgeryToken]
        public ActionResult LoginPost(Faculty empleado)
        {
            if (ModelState.IsValid)
            {
                using (Cafeteria_POSEntities context = new Cafeteria_POSEntities())
                {
                    var user = context.Faculties.Where(e => e.Email.Equals(empleado.Email)
                        && e.Password.Equals(empleado.Password)).FirstOrDefault();
                    if (user != null)
                    {
                        Session["UserID"] = user.Employee_ID.ToString();
                        Session["User_Email"] = user.Email.ToString();
                        Session["User_FirstName"] = user.First_Name.ToString();
                        Session["User_LastName"] = user.Last_Name.ToString();
                        return RedirectToAction("UserDashBoard");
                    }
                    else
                    {
                        return RedirectToAction("Login");
                    }
                }
            }
            return View(empleado);
        }


        [HttpGet]
        public ActionResult UserDashBoard()
        {
            return View();
        }

        [HttpPost]
        [ActionName("UserDashBoardPost")]
        public ActionResult UserDashBoardPost()
        {
            if (Session["User_Email"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login");
            }
        }
    }

    //j.maltez1@keiseruniversity.edu
    //password123
}

Controllers/Administrators/KU_StudentsController.cs
using POS.Datos;
using POS.Models;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace POS.Controllers
{
    public class KU_StudentsController : Controller
    {
        KU_StudentsAdmin admin = new KU_StudentsAdmin();

        // GET: KU_Students
        public ActionResult Index()
        {
            return View(admin.Consultar());
        }

        [HttpGet]
        public ActionResult Nuevo()
        {
            ViewBag.Meal_Plan = GetPlanesSelect();
            admin.Consultar();
            return View();
        }

        [HttpPost]
        [ActionName("Guardar")]
        public ActionResult NuevoPost(KU_Students ku_Student)
        {
            if (ModelState.IsValid)
            {
                admin.Consultar();
                using (Cafeteria_POSEntities context = new Cafeteria_POSEntities()) 
                {
                    context.KU_Students.Add(ku_Student);
                    context.SaveChanges();
                    ViewBag.mensaje = "Informacion Guardada";
                    return RedirectToAction("Index");
                }
                
            }
            return View(ku_Student);
        }

        public ActionResult Guardar() // HTTP GET
        {
            ViewBag.mansaje = "";
            ViewBag.Meal_Plan = GetPlanesSelect();
            return View();
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            Cafeteria_POSEntities context = new Cafeteria_POSEntities();
            KU_Students ku_Student = context.KU_Students.Single(x => x.Student_ID == id);
            ViewBag.Meal_Plan = GetPlanesSelect();
            return View(ku_Student);
        }

        [HttpPost]
        [ActionName("Editar")]
        public ActionResult Editar(KU_Students ku_Student)
        {
            if (ModelState.IsValid)
            {
                Cafeteria_POSEntities context = new Cafeteria_POSEntities();
                context.Entry(ku_Student).State = EntityState.Modified; 
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ku_Student);
        }

        public IEnumerable<SelectListItem> GetPlanesSelect()
        {
            using (Cafeteria_POSEntities Context = new Cafeteria_POSEntities())
            {
                return Context.Plans.Select(plan => new SelectListItem { Value = plan.Plan_Name, Text = plan.Plan_Name }).ToList();
            }
        }

        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            Cafeteria_POSEntities context = new Cafeteria_POSEntities();
            KU_Students ku_Student = context.KU_Students.Single(x => x.Student_ID == id);
            return View(ku_Student);
        }

        [HttpPost]
        [ActionName("Eliminar")]
        public ActionResult EliminarConfirm(int id)
        {
            Cafeteria_POSEntities context = new Cafeteria_POSEntities();
            KU_Students ku_Student = context.KU_Students.Single(x => x.Student_ID == id);
            context.KU_Students.Remove(ku_Student);
            context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

Controllers/Administrators/Languague_StudentsController.cs
using POS.Datos;
using POS.Models;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace POS.Controllers
{
    public class Languague_StudentsController : Controller
    {
        Language_StudentsAdmin admin = new Language_StudentsAdmin();

        // GET: Languague_Students
        public ActionResult Index()
        {
            return View(admin.Consultar());
        }

        [HttpGet]
        public ActionResult Nuevo()
        {
            ViewBag.Meal_Plan = GetPlanesSelect();
            admin.Consultar();
            return View();
        }

        [HttpPost]
        [ActionName("Guardar")]
        public ActionResult NuevoPost(Language_Students Lang_Student)
        {
            if (ModelState.IsValid)
            {
                admin.Consultar();
                using (Cafeteria_POSEntities context = new Cafeteria_POSEntities())
                {
                    context.Language_Students.Add(Lang_Student);
                    context.SaveChanges();
                    ViewBag.mensaje = "Informacion Guardada";
                    return RedirectToAction("Index");
                }
            }
            return View(Lang_Student);
        }

        [HttpGet]
        public ActionResult Guardar() // HTTP GET
        {
            ViewBag.mensaje = "";
            ViewBag.Meal_Plan = GetPlanesSelect();
            return View();
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            Cafeteria_POSEntities context = new Cafeteria_POSEntities();
            Language_Students Lang_Student = context.Language_Students.Single(x => x.Student_ID == id);
            ViewBag.Meal_Plan = GetPlanesSelect();
            return View(Lang_Student);
        }


        [HttpPost]
        [ActionName("Editar")]
        public ActionResult Editar(Language_Students Lang_Student)
        {
            if (ModelState.IsValid)
            {
                Cafeteria_POSEntities context = new Cafeteria_POSEntities();
                context.Entry(Lang_Student).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(Lang_Student);

        }

        public IEnumerable<SelectListItem> GetPlanesSelect()
        {
            using (Cafeteria_POSEntities Context = new Cafeteria_POSEntities())
            {
                return Context.Plans.Select(plan => new SelectListItem { Value = plan.Plan_Name, Text = plan.Plan_Name }).ToList();
            }
        }

        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            Cafeteria_POSEntities context = new Cafeteria_POSEntities();
            Language_Students Lang_Student = context.Language_Students.Single(x => x.Student_ID == id);
            return View(Lang_Student);
        }

        [HttpPost]
        [ActionName("Eliminar")]
        public ActionResult EliminarConfirm(int id)
        {
            Cafeteria_POSEntities context = new Cafeteria_POSEntities();
            Language_Students Lang_Student = context.Language_Students.Single(x => x.Student_ID == id);
            context.Language_Students.Remove(Lang_Student);
            context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

Views/Faculty/Detalles.cshtml
@model POS.Models.Faculty

@{
    ViewBag.Title = "Detalles";
}

<h2>Detalles del Usuario</h2>

<div>
    <h4>Faculty</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Organization_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Organization_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.First_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.First_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Last_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Last_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Job_Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Job_Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone_Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone_Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Meal_Plan_Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Meal_Plan_Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Plan.Plan_Days)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Plan.Plan_Days)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Employee_ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Faculty/Guardar.cshtml
@model POS.Models.Faculty

@{
    ViewBag.Title = "Guardar";
}

<h2>Guardar Nuevo Integrante de Facultad KU</h2>

@using (Html.BeginForm("Guardar","Faculty",FormMethod.Post)) //Metodo "Nuevo", Controlador "Producto", Accion "HTTP POST"
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Faculty</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Organization_Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Organization_Name, new { htmlAttributes = new { @class = "form-control", placeholder = "", required = "required" } })
            @Html.ValidationMessageFor(model => model.Organization_Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.First_Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.First_Name, new { htmlAttributes = new { @class = "form-control", placeholder = "", required = "required" } })
            @Html.ValidationMessageFor(model => model.First_Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Last_Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Last_Name, new { htmlAttributes = new { @class = "form-control", placeholder = "", required = "required" } })
            @Html.ValidationMessageFor(model => model.Last_Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Job_Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Job_Title, new { htmlAttributes = new { @class = "form-control", placeholder = "", required = "required" } })
            @Html.ValidationMessageFor(model => model.Job_Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = "", required = "required" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.IsActive)
                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control", placeholder = "", required = "required" } })
            @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", placeholder = "", required = "required" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Phone_Number, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Phone_Number, new { htmlAttributes = new { @class = "form-control", placeholder = "", required = "required" } })
            @Html.ValidationMessageFor(model => model.Phone_Number, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Meal_Plan, "Meal_Plan", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Meal_Plan", null, htmlAttributes: new { @class = "form-control", placeholder = "", required = "required" })
            @Html.ValidationMessageFor(model => model.Meal_Plan, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Meal_Plan_Status, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Meal_Plan_Status)
                @Html.ValidationMessageFor(model => model.Meal_Plan_Status, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar" class="btn btn-default" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <font color="green">@ViewBag.mensaje</font>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Faculty/Login.cshtml
@model POS.Models.Faculty

@{
    ViewBag.Title = "Login";
}

<link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sign-in/">
<!-- Bootstrap core CSS -->
<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

<style>
        html,
        body {
            height: 100%;
        }

    body {
        color: white;
        display: flex;
        align-items: center;
        padding-top: 40px;
        padding-bottom: 40px;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-wrap: wrap;
        width: 1300px;
        background: #232427;
    }

        .form-signin {
            width: 100%;
            max-width: 270px;
            padding: 15px;
            margin: auto;
        }

        .form-signin .checkbox {
            font-weight: 400;
        }

        .form-signin .form-floating:focus-within {
            z-index: 2;
        }

        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }

        .btn-lg, .btn-group-lg > .btn {
            padding: 13px 16px;
            font-size: 18px;
            line-height: 1.3333333;
            border-radius: 10px;
            margin-right:30px;
            margin-left: 30px;
        }
</style>


@using (Html.BeginForm("Iniciar Sesion", "Faculty", FormMethod.Post))
{
    <fieldset>
        <legend></legend>

        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        @if (@ViewBag.Message != null)
        {
            <div style="border: 1px solid red">
                @ViewBag.Message
            </div>
        }

        <!--
            <table>
                <tr>
                    <td>@Html.LabelFor(a => a.Email)</td>
                    <td>@Html.TextBoxFor(a => a.Email)</td>
                    <td>@Html.ValidationMessageFor(a => a.Email)</td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(a => a.Password)
                    </td>
                    <td>
                        @Html.PasswordFor(a => a.Password)
                    </td>
                    <td>
                        @Html.ValidationMessageFor(a => a.Password)
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <input type="submit" value="Login" />
                    </td>
                    <td></td>
                </tr>
            </table>
        -->
        <html lang="en">
        <body class="text-center">
            <main class="form-signin">
                <form>
                    <h1 class="h3 mb-3 fw-normal">Please Log In</h1>

                    <br />

                    <div class="form-floating">
                        @Html.LabelFor(a => a.Email, "", new { @for = "floatingInput" })
                        @Html.TextBoxFor(a => a.Email, "", new { @class = "form-control", @id = "floatingInput", @placeholder = "username@example.com", @type = "email" })
                        @Html.ValidationMessageFor(a => a.Email, "", new { @class = "" })
                        <!--
        <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com" />
         -->
                    </div>

                    <br />

                    <div class="form-floating">
                        @Html.LabelFor(a => a.Password, "", new { @for = "floatingPassword" })
                        <!--
                            <input type="password" class="form-control" id="floatingPassword" placeholder="Password", />
                        -->
                        @Html.PasswordFor(a => a.Password, new { @class = "form-control", @id = "floatingPassword", @placeholder = "Password", @type = "password" })
                        @Html.ValidationMessageFor(a => a.Password)
                    </div>

                    <br />

                    <button class="w-100 btn btn-lg btn-primary" type="submit" value="Login">Sign in</button>
                </form>
            </main>
        </body>
    </html>

</fieldset>
}

Views/Faculty/UserDashBoard.cshtml
@model POS.Models.Faculty

@{
    ViewBag.Title = "UserDashBoard";
}

<style>

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: "Poppins", sans-serif;
}

body {
  display: flex;
  justify-content: center;
  align-items: center;
  flex-wrap: wrap;
  width: 1300px;
  background: #232427;
}

    body .container {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-wrap: wrap;
        max-width: 1200px;
        margin: 40px 0;
    }

body .container .card {
  position: relative;
  min-width: 320px;
  height: 440px;
  box-shadow: inset 5px 5px 5px rgba(0, 0, 0, 0.2),
    inset -5px -5px 15px rgba(255, 255, 255, 0.1),
    5px 5px 15px rgba(0, 0, 0, 0.3), -5px -5px 15px rgba(255, 255, 255, 0.1);
  border-radius: 15px;
  margin: 30px;
}

body .container .card:nth-child(1) .box .content a {
  background: #2196f3;
}

body .container .card:nth-child(2) .box .content a {
  background: #e91e63;
}

body .container .card:nth-child(3) .box .content a {
  background: #23c186;
}

body .container .card .box {
  position: absolute;
  top: 20px;
  left: 20px;
  right: 20px;
  bottom: 20px;
  background: #2a2b2f;
  border-radius: 15px;
  display: flex;
  justify-content: center;
  align-items: center;
  overflow: hidden;
  transition: 0.5s;
}

body .container .card .box:hover {
  transform: translateY(-50px);
}

body .container .card .box:before {
  content: "";
  position: absolute;
  top: 0;
  left: 0;
  width: 50%;
  height: 100%;
  background: rgba(255, 255, 255, 0.03);
}

body .container .card .box .content {
  padding: 20px;
  text-align: center;
}

body .container .card .box .content h2 {
  position: absolute;
  top: -10px;
  right: 30px;
  font-size: 8rem;
  color: rgba(255, 255, 255, 0.1);
}

body .container .card .box .content h3 {
  font-size: 1.8rem;
  color: #fff;
  z-index: 1;
  transition: 0.5s;
  margin-bottom: 15px;
}

body .container .card .box .content p {
  font-size: 12px;
  font-weight: 400;
  color: rgba(255, 255, 255, 0.9);
  z-index: 1;
  transition: 0.5s;
}

body .container .card .box .content a {
  position: relative;
  display: inline-block;
  padding: 8px 20px;
  background: black;
  border-radius: 5px;
  text-decoration: none;
  color: white;
  margin-top: 20px;
  box-shadow: 0 10px 20px rgba(0, 0, 0, 0.2);
  transition: 0.5s;
}
body .container .card .box .content a:hover {
  box-shadow: 0 10px 20px rgba(0, 0, 0, 0.6);
  background: #fff;
  color: #000;
}

    .h3 {
        text-align: left;
        color: white;
        box-shadow: 0 10px 20px rgba(0, 0, 0, 0.2);
        border-radius: 5px;
    }

    .h2 {
        text-align: center;
        color: white;
        box-shadow: 0 10px 20px rgba(0, 0, 0, 0.2);
        border-radius: 5px;
    }

</style>

<h2 class="h2">Admin DashBoard</h2>

<fieldset>

    @if (Session["User_Email"] != null)
    {
        <div>
            <h3 class="h3">
                Welcome @Session["User_FirstName"].ToString()
            </h3>
        </div>
    }

    <div class="container">
        <div class="card">
            <div class="box">
                <div class="content">
                    <h2>KU</h2>
                    <h3>Keiser University Faculty Members</h3>
                    <p>This is the list of all faculty members of KULAC</p>
                    @Html.ActionLink("Keiser University Faculty", "Index")
                </div>
            </div>
        </div>

        <div class="card">
            <div class="box">
                <div class="content">
                    <h2>KU</h2>
                    <h3>Keiser University Students</h3>
                    <p>This is the list of all student body´s member of KULAC</p>
                    @Html.ActionLink("Keiser University Students", "Index", "KU_Students")
                </div>
            </div>
        </div>

        <div class="card">
            <div class="box">
                <div class="content">
                    <h2>KU</h2>
                    <h3>Language Institute Students</h3>
                    <p>This is the list of all student body´s member of Language Institute</p>
                    @Html.ActionLink("Language Students", "Index", "Languague_Students")
                </div>
            </div>
        </div>
    </div>

</fieldset>